server:
  port: 2001

spring:
  application:
    name: provider-2001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    #注册到多个服务注册中心 eureka.client.serviceUrl.defaultZone=http://peer1:1001/eureka/,http://peer2:1002/eureka/

test:
  myname: qgw-999
